apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    type: web
spec:
  containers:
  - name: cont-web
    image: nginx
    ports:
    - containerPort: 80
  - name: logger
    image: fluent/fluentd
