apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-nginx-pvc
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: demo-nginx-pvc
  targetCPUUtilizationPercentage: 60
