apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-nginx-pvc
  name: demo-nginx-pvc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-nginx-pvc
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
          - name: SECRET_ENV
            valueFrom:
              secretKeyRef:
                name: test-secret
                key: clienttoken
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/tmp"
          name: my-volume
        ports:
        - containerPort: 80
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: pv-claim
